on: [push, pull_request]
name: iOS
jobs:
  Integration:
    name: "Integration (${{ matrix.runs_on }}, ${{ matrix.python }})"
    runs-on: ${{ matrix.runs_on }}
    strategy:
      fail-fast: false
      matrix:
        # macos-15-intel runs on Intel.
        # All others run on Apple Silicon (ARM).
        runs_on: [macos-latest, macos-15-intel, macos-26]
        python: [3.x]
    steps:
    - name: "Setup Python ${{ matrix.python }} on ${{ matrix.runs_on }} (${{ runner.arch }})"
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python }}
    - uses: actions/checkout@v5
    - name: Setup environment
      run: |
        pip install .[ios]
    - name: Check buildozer installation
      run: |
        buildozer --help
    - name: Initialize buildozer in project folder
      run: |
        buildozer init
    - name: Install dependencies
      run: |
        brew install autoconf automake libtool pkg-config
    - name: buildozer ios debug
      run: |
        touch main.py
        buildozer ios debug
